spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://10.1.204.33:3306/demo?useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml

server:
  port: 9890